### ISSUE TITLE
Time conversion min to hours is incorrect 

### ISSUE THREAD

**Issue by crdgom** [iterami/UnitConverter.htm#8]
Hello, in the conversion you do the formula (minute * 1) / 3600 = 0.0327 ...

! [image] (https://user-images.githubusercontent.com/5928931/131588225-3d75b573-1c78-43b8-8839-e0328341e03a.png)

The correct formula is (minute * 60) / 3600 = 1.9666 ...

! [image] (https://user-images.githubusercontent.com/5928931/131588366-af10e62a-7ccd-4703-bd66-9d48815bb442.png)

And for me the last formula is wrong, when we want to convert minutes to hours, we don't want the result in percentage, we expect the result to return like this 118 min = 1 hour 58 minutes

Cheers

**Comment by honzi** [comment]
Hello. In your first screenshot it seems you are converting from seconds to hours instead of minutes to hours. I rechecked both of those formulas compared to google search results and they seem to be working correctly.

Regarding the formula returning multiple units: I agree that may be useful in certain situations and even opened an issue for it (#5), but that would require a lot of changes to the UI and parsing that haven't even begun to be planned yet. Conversation can be continued there, so I'll mark this as closed for now.
